name       : libuiohook
version    : 1.0.3
release    : 1
source     :
    - https://github.com/kwhat/libuiohook/archive/1.0.3.tar.gz : 891f186cc43c04bfe1d3c192841682a709a256dc03871628980483b1a0f32dec
license    : GPL-3.0
component  : programming.library
summary    : A multi-platform C library to provide global keyboard and mouse hooks from userland.
description: |
    A multi-platform C library to provide global keyboard and mouse hooks from userland.
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xkbfile)
    - pkgconfig(xrandr)
    - pkgconfig(xt)
    - pkgconfig(xtst)
setup      : |
    %reconfigure --disable-static --enable-test
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
